// generated by bake_dialogue.py -- do not hand-edit
printl("[dlg] boxes table loaded: baked 2026-08-20 02:46:33, 1 boxes, row0-reserved");
::DialogueBoxes <- {
	"test": { row0 = 1, rows = 3, total = 768, steps = [7,13,15,17,23,38,44,49,51,58,264,270,281,284,290,296,302,308,314,325,331,341,348,359,365,372,383,389,395,401,411,418,423,428,435,519,525,531,537,543,549,555,561,567,573,579,585,591,593,595,597,599] },
}
